/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/test": {
    post: operations["TestController_checkIn"];
  };
  "/api/image/{imageSize}/{imageName}": {
    /** Получение трендов фильмов/сериалов */
    get: operations["ImageController_getImage"];
  };
  "/api/auth/local/signup": {
    /** Регистрация пользователя */
    post: operations["AuthController_signupLocal"];
  };
  "/api/auth/local/signup/confirmation": {
    /** Подтверждение регистрации пользователя */
    post: operations["AuthController_signupConfirmation"];
  };
  "/api/auth/local/signin": {
    /** Авторизация пользователя */
    post: operations["AuthController_signinLocal"];
  };
  "/api/auth/logout": {
    /** Выход из профиля */
    post: operations["AuthController_logout"];
  };
  "/api/auth/refresh": {
    /** Обновления accessToken */
    post: operations["AuthController_refreshTokens"];
  };
  "/api/auth/restore-password-link": {
    /** Ссылка на восстановление пароля */
    post: operations["AuthController_restorePasswordLink"];
  };
  "/api/auth/restore-password": {
    /** Восстановление пароля */
    post: operations["AuthController_restorePassword"];
  };
  "/api/auth/google": {
    /** Авторизация через Google */
    get: operations["AuthController_signinGoogle"];
  };
  "/api/auth/google/redirect": {
    /** Callback для Google */
    get: operations["AuthController_googleRedirect"];
  };
  "/api/users/{id}": {
    /** Получение данных пользователя */
    get: operations["UsersController_getUser"];
    /** Удаление пользователя */
    delete: operations["UsersController_deleteUser"];
    /** Редактирование данных пользователя */
    patch: operations["UsersController_editUser"];
  };
  "/api/users": {
    /** Получение данных пользователей */
    post: operations["UsersController_getUsers"];
  };
  "/api/mailer/confirmation": {
    /** Отправка кода подтверждения */
    post: operations["MailerController_test"];
  };
  "/api/file": {
    /** Загрузка файлов на сервер */
    post: operations["MinIOController_uploadFile"];
    /** Удаление файлов с сервера */
    delete: operations["MinIOController_deleteFile"];
  };
  "/api/parser/parse": {
    /** Парсинг торрентов по фильму/сериалу из запроса */
    post: operations["ParserController_parsePictureTorrents"];
  };
  "/api/parser": {
    /** Получение торрент файлов по заданному запросу */
    post: operations["ParserController_getPictureTorrents"];
  };
  "/api/person/{tmdbId}": {
    /** Получение данных по Личности */
    get: operations["PersonController_getPersonData"];
  };
  "/api/picture": {
    /** Поиск фильма/сериала по запросу */
    get: operations["PictureController_search"];
  };
  "/api/picture/{tmdbId}/{mediaType}": {
    /** Получение даных о фильме/сериале */
    get: operations["PictureController_getPictureData"];
  };
  "/api/picture/trends/{mediaType}/{timeWindow}": {
    /** Получение трендов фильмов/сериалов */
    get: operations["PictureController_getPictureTrends"];
  };
  "/api/picture/network/{mediaType}/{network}": {
    /** Получение фильмов/сериалов определенной компании */
    get: operations["PictureController_getNetworkPictures"];
  };
  "/api/picture/recent-viewed": {
    /** Получение перечня недавно просматриваемых фильмов/сериалов */
    get: operations["PictureController_getRecentViewedPictures"];
  };
  "/api/webtorrent": {
    /** Получение информации о торрент файле */
    get: operations["WebtorrentController_getTorrentInfo"];
  };
  "/api/preview": {
    /** JSON объект трендов Фильмов/Сериалов для Samsung PublicPreview */
    get: operations["PublicPreviewController_getPreview"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignupLocalDto: {
      userName: string;
      email: string;
      password: string;
    };
    ErrorDto: {
      statusCode: number;
      message: string;
      error?: string;
    };
    ActivationDto: {
      activationToken: string;
      activationCode: string;
    };
    TokensDto: {
      accessToken: string;
      refreshToken: string;
    };
    SigninLocalDto: {
      email: string;
      password: string;
    };
    RestorePasswordLinkDto: {
      email: string;
    };
    RestorePasswordDto: {
      restorePasswordToken: string;
      newPassword: string;
    };
    UserWithoutPasswordDto: {
      _id: string;
      /** @enum {string} */
      role: "admin" | "guest" | "member" | "premium" | "blocked";
      email: string;
      userName?: string | null;
      image?: string | null;
    };
    WrappedUserDto: {
      user: components["schemas"]["UserWithoutPasswordDto"];
    };
    UsersEmailDto: {
      users: string[];
    };
    WrappedUsersDto: {
      users: components["schemas"]["UserWithoutPasswordDto"][];
    };
    Response: {
      _id: string;
      /** @enum {string} */
      role: "admin" | "guest" | "member" | "premium" | "blocked";
      email: string;
      userName?: string | null;
      image?: string | null;
    };
    EmailDto: {
      to: string;
      subject: string;
      text: string;
    };
    FileUrlDto: Record<string, never>;
    DeletedFileDto: Record<string, never>;
    DeletingConfirmDto: Record<string, never>;
    ParsePictureTorrentsRequestDto: {
      tmdbId: string;
      imdbId?: string | null;
      /** @enum {string} */
      mediaType: "all" | "movie" | "tv" | "person";
      searchQuery: string;
    };
    TorrentDto: {
      name: string;
      size: string | null;
      link: string | null;
      seeders: string | null;
      leeches: string | null;
    };
    GetTorrentsResponseDto: {
      trackerLabel: string;
      torrents: components["schemas"]["TorrentDto"][];
      /** @enum {string} */
      trackerStatus: "created" | "updating" | "finished" | "warning" | "error";
      lastUpdate: string;
      trackerMessage: string | null;
    };
    ParsePictureTorrentsResponseDto: {
      searchQuery: string;
      /** @enum {string} */
      searchStatus: "created" | "updating" | "finished" | "warning" | "error";
      trackers: components["schemas"]["GetTorrentsResponseDto"][][];
      message: string | null;
    };
    GetTorrentsRequestDto: {
      tmdbId: string;
      imdbId?: string | null;
      /** @enum {string} */
      mediaType: "all" | "movie" | "tv" | "person";
      searchQuery: string;
    };
    PersonDetailDataDto: Record<string, never>;
    MovieSlim: {
      tmdbId: string;
      /**
       * @default movie
       * @enum {string}
       */
      mediaType: "all" | "movie" | "tv" | "person";
      logoPath: string | null;
      posterPath: string | null;
      hPosterPath: string | null;
      purePosterPath: string | null;
      pureHPosterPath: string | null;
      backdropPath: string | null;
      title: string;
      originalTitle: string;
      overview: string | null;
      genres: number[];
      releaseDate: string;
      popularity: number;
      voteAverage: number;
      trailer: string | null;
    };
    TvSlim: {
      tmdbId: string;
      /**
       * @default tv
       * @enum {string}
       */
      mediaType: "all" | "movie" | "tv" | "person";
      logoPath: string | null;
      posterPath: string | null;
      hPosterPath: string | null;
      purePosterPath: string | null;
      pureHPosterPath: string | null;
      backdropPath: string | null;
      title: string;
      originalTitle: string;
      overview: string;
      genres: number[];
      releaseDate: string;
      popularity: number;
      voteAverage: number;
      trailer: string | null;
    };
    PersonSlim: {
      tmdbId: string;
      /**
       * @default person
       * @enum {string}
       */
      mediaType: "all" | "movie" | "tv" | "person";
      name: string;
      profilePath: string | null;
      popularity: number;
    };
    SearchResultDto: {
      page: number;
      totalPages: number;
      totalResults: number;
      results: (components["schemas"]["MovieSlim"] | components["schemas"]["TvSlim"] | components["schemas"]["PersonSlim"])[];
    };
    GenresDto: {
      id: number;
      name: string;
    };
    CompanyDto: {
      id: number;
      name: string;
      logoPath: string | null;
    };
    VideoDto: {
      iso?: string;
      name: string;
      key: string;
      site: string;
      size: number;
      type: string;
      official: boolean;
      publishedAt: string;
    };
    ResultsVideoObjDto: {
      results: components["schemas"]["VideoDto"][];
    };
    ParticipantPersonDto: {
      tmdbId: number;
      department: string;
      job: string | null;
      name: string;
      originalName: string;
      character: string | null;
      popularity: number;
      profilePath: string | null;
    };
    CreditsDto: {
      cast: components["schemas"]["ParticipantPersonDto"][];
      crew: components["schemas"]["ParticipantPersonDto"][];
    };
    ImageDto: {
      aspectRatio: number;
      filePath: string;
      height: number;
      iso: string | null;
      voteAverage: number;
      width: number;
    };
    ImagesDto: {
      backdrops: components["schemas"]["ImageDto"][];
      logos: components["schemas"]["ImageDto"][];
      posters: components["schemas"]["ImageDto"][];
    };
    MovieDto: {
      backdropPath: string | null;
      budget: number;
      genres: components["schemas"]["GenresDto"][];
      originalTitle: string;
      overview: string | null;
      popularity: number;
      posterPath: string | null;
      production: components["schemas"]["CompanyDto"][];
      releaseDate: string;
      revenue: number;
      runtime: number | null;
      /** @enum {string} */
      status: "Rumored" | "Planned" | "In Production" | "Post Production" | "Released" | "Canceled";
      tagline: string | null;
      title: string;
      voteAverage: number;
      videos: components["schemas"]["ResultsVideoObjDto"];
      credits: components["schemas"]["CreditsDto"];
      images: components["schemas"]["ImagesDto"];
    };
    GetPictureResponseDto: {
      tmdbId: string;
      imdbId?: string | null;
      /** @enum {string} */
      mediaType: "all" | "movie" | "tv" | "person";
      pictureData: components["schemas"]["MovieDto"];
    };
    GetPictureTrendsResponseDto: {
      page: number;
      totalPages: number;
      totalResults: number;
      results: (components["schemas"]["MovieSlim"] | components["schemas"]["TvSlim"] | components["schemas"]["PersonSlim"])[];
    };
    GetNetworkPicturesResponseDto: {
      page: number;
      totalPages: number;
      totalResults: number;
      results: (components["schemas"]["MovieSlim"] | components["schemas"]["TvSlim"])[];
    };
    GetTorrentDistributionInfoRequestDto: {
      tmdbId: string;
      imdbId?: string | null;
      /** @enum {string} */
      mediaType: "all" | "movie" | "tv" | "person";
    };
    GetTorrentDistributionInfoResponseDto: Record<string, never>;
    GetPreviewResultDto: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  TestController_checkIn: {
    responses: {
      201: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** Получение трендов фильмов/сериалов */
  ImageController_getImage: {
    parameters: {
      path: {
        imageSize: string;
        imageName: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Регистрация пользователя */
  AuthController_signupLocal: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupLocalDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Подтверждение регистрации пользователя */
  AuthController_signupConfirmation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActivationDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["TokensDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Авторизация пользователя */
  AuthController_signinLocal: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SigninLocalDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokensDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Выход из профиля */
  AuthController_logout: {
    responses: {
      200: {
        content: {
          "application/json": boolean;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Обновления accessToken */
  AuthController_refreshTokens: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokensDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Ссылка на восстановление пароля */
  AuthController_restorePasswordLink: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RestorePasswordLinkDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": boolean;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Восстановление пароля */
  AuthController_restorePassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RestorePasswordDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": boolean;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Авторизация через Google */
  AuthController_signinGoogle: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Callback для Google */
  AuthController_googleRedirect: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение данных пользователя */
  UsersController_getUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WrappedUserDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Удаление пользователя */
  UsersController_deleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": boolean;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Редактирование данных пользователя */
  UsersController_editUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserWithoutPasswordDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение данных пользователей */
  UsersController_getUsers: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UsersEmailDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["WrappedUsersDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Отправка кода подтверждения */
  MailerController_test: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": boolean;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Загрузка файлов на сервер */
  MinIOController_uploadFile: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["FileUrlDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Удаление файлов с сервера */
  MinIOController_deleteFile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeletedFileDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DeletingConfirmDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Парсинг торрентов по фильму/сериалу из запроса */
  ParserController_parsePictureTorrents: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParsePictureTorrentsRequestDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ParsePictureTorrentsResponseDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение торрент файлов по заданному запросу */
  ParserController_getPictureTorrents: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetTorrentsRequestDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["GetTorrentsResponseDto"][];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение данных по Личности */
  PersonController_getPersonData: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PersonDetailDataDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Поиск фильма/сериала по запросу */
  PictureController_search: {
    parameters: {
      query: {
        query: string;
        mediaType: "all" | "movie" | "tv" | "person";
        page?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SearchResultDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение даных о фильме/сериале */
  PictureController_getPictureData: {
    parameters: {
      query?: {
        imdbId?: string | null;
        /** @description May contain additional data in the request - "videos,images,credits" */
        appends?: string;
      };
      path: {
        tmdbId: string;
        mediaType: "all" | "movie" | "tv" | "person";
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetPictureResponseDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение трендов фильмов/сериалов */
  PictureController_getPictureTrends: {
    parameters: {
      query?: {
        page?: number;
      };
      path: {
        mediaType: "all" | "movie" | "tv" | "person";
        timeWindow: "day" | "week";
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetPictureTrendsResponseDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение фильмов/сериалов определенной компании */
  PictureController_getNetworkPictures: {
    parameters: {
      query?: {
        page?: number;
      };
      path: {
        mediaType: "all" | "movie" | "tv" | "person";
        network: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetNetworkPicturesResponseDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение перечня недавно просматриваемых фильмов/сериалов */
  PictureController_getRecentViewedPictures: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetPictureResponseDto"][];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Получение информации о торрент файле */
  WebtorrentController_getTorrentInfo: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetTorrentDistributionInfoRequestDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetTorrentDistributionInfoResponseDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** JSON объект трендов Фильмов/Сериалов для Samsung PublicPreview */
  PublicPreviewController_getPreview: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetPreviewResultDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
}
